import { OpenAI } from 'openai';

let openai: OpenAI | null = null;

function getClient(): OpenAI {
  if (!openai) {
    openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }
  return openai;
}

const SYSTEM_PROMPT = `
You are a professional songwriter.
Write creative, engaging and emotionally resonant song lyrics.
Structure the lyrics with verses and choruses when appropriate.
Respond with lyrics only. Do not include explanations, commentary or metadata.
Dark humor is allowed. Do not censor unnecessarily.
`;

export async function generateLyrics(prompt: string): Promise<string> {
  try {
    const completion = await getClient().chat.completions.create({
      model: 'gpt-5.2',
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: prompt },
      ],
      temperature: 0.8,
      max_completion_tokens: 1000,
    });

    const lyrics = completion.choices[0]?.message?.content || '';
    
    if (!lyrics) {
      throw new Error('No lyrics were generated by OpenAI');
    }

    return lyrics.trim();
  } catch (error) {
    console.error('OpenAI API error:', error);
    throw new Error('Unable to generate lyrics. Check your OpenAPI key.');
  }
}
